let data = [{
  "id": 31,
  "order": 1,
  "product_name": 'Galaxy S23',
  "make": "Samsung",
  "memory": "128GB",
  "os": "Android",
  "ram": "8GB",
  "price": 800,
  "image": '/Images/5 Deals/galaxy-s23.png',
  "title": "Smartphone",
  "isNew":false,
  "wn": '3G, 4G LTE',
},{
  "id": 32,
  "order": 1,
  "product_name": 'Apple watch series 8',
  "make": "Apple",
  "memory": "32GB",
  "os": "iOS",
  "ram": "8GB",
  "price": 750,
  "image": '/Images/5 Deals/apple-watch.png',
  "title": "Watch",
  "isNew":false,
  "wn": '3G, 4G LTE',
},{
  "id": 33,
  "order": 1,
  "product_name": 'Galaxy Tab S8+ 5G' ,
  "make": "Samsung",
  "memory": "128GB",
  "os": "Android",
  "ram": "8GB",
  "price": 650,
  "image": '/Images/5 Deals/Galaxy Tab S8.png',
  "title": "Tablet",
  "isNew":false,
  "wn": '3G, 4G LTE',
},{
  "id": 34,
  "order": 1,
  "product_name": 'iPhone 13 Pro Max' ,
  "make": "Apple",
  "memory": "256GB",
  "os": "iOS",
  "ram": "8GB",
  "price": 650,
  "image": '/Images/5 Deals/iPhone 13 Pro Max.png',
  "title": "Smartphone",
  "isNew":false,
  "wn": '3G, 4G LTE',
}]  

export const dealsAPI = data