let data = [{
    "id": 1,
    "product_name": "Xiaomi Redmi Note 12",
    "make": "Xiaomi Redmi",
    "memory": "128G",
    "os": "Android",
    "ram": "8GB",
    "price": 180,
    "image": "/Images/smartphones/xiaomi-redmi-note12-8.jpg",
    "title": "Smartphone",
    "isNew":false,
  }, {
    "id": 2,
    "product_name": "Xiaomi Redmi Note 11S",
    "make": "Xiaomi Redmi",
    "memory": "128GB",
    "os": "Android",
    "ram": "8GB",
    "price": 190,
    "image": "/Images/smartphones/xiaomi-redmi-note-11s.jpg",
    "title": "Smartphone",
    "isNew":false,
  }, {
    "id": 3,
    "product_name": "Xiaomi Redmi A2 Plus",
    "make": "Xiaomi Redmi",
    "memory": "32GB",
    "os": "Android",
    "ram": "2GB",
    "price": 79,
    "image": "/Images/smartphones/xiaomi-redmi-a2-plus.webp",
    "title": "Smartphone",
    "isNew":false,
  }, {
    "id": 4,
    "product_name": "Xiaomi Redmi Note 10",
    "make": "Xiaomi Redmi",
    "memory": "64GB",
    "os": "Android",
    "ram": "4GB",
    "price": 150,
    "image": "/Images/smartphones/xiaomi-redmi-note10.jpg",
    "title": "Smartphone",
    "wn": "5G",
  }, {
    "id": 5,
    "product_name": "Xiaomi Redmi A1 Plus",
    "make": "Xiaomi Redmi",
    "memory": "32GB",
    "os": "Android",
    "ram": "2GB",
    "price": 150,
    "image": "/Images/smartphones/xiaomi-redmi-a1-plus.jpg",
    "title": "Smartphone",
    "wn": "4G",
  }, {
    "id": 6,
    "product_name": "Xiaomi Redmi 9A",
    "make": "Xiaomi Redmi",
    "memory": "32GB",
    "os": "Android",
    "ram": "2GB",
    "price": 80,
    "image": "/Images/smartphones/xiaomi-redmi-9a.jpg",
    "title": "Smartphone",
    "wn": "4G",
  }, {
    "id": 7,
    "product_name": "Xiaomi Redmi 12X",
    "make": "Xiaomi Redmi",
    "memory": "256GB",
    "os": "Android",
    "ram": "8GB",
    "price": 450,
    "image": "/Images/smartphones/xiaomi-redmi-12xpng.png",
    "title": "Smartphone",
    "wn": "5G",
  }, {
    "id": 8,
    "product_name": "Xiaomi Redmi 12C",
    "make": "Xiaomi Redmi",
    "memory": "64GB",
    "os": "Android",
    "ram": "4GB",
    "price": 110,
    "image": "/Images/smartphones/xiaomi-redmi-12c.jpg",
    "title": "Smartphone",
    "wn": "4G",
  }, {
    "id": 9,
    "product_name": "Xiaomi Redmi 12Pro",
    "make": "Xiaomi Redmi",
    "memory": "256GB",
    "os": "Android",
    "ram": "12GB",
    "price": 810,
    "image": "/Images/smartphones/xiaomi-redmi-12pro.jpg",
    "title": "Smartphone",
    "wn": "5G",
  }, {
    "id": 10,
    "product_name": "Xiaomi Poco X5",
    "make": "Xiaomi Redmi",
    "memory": "256GB",
    "os": "Android",
    "ram": "8GB",
    "price": 250,
    "image": "/Images/smartphones/xiaomi-redmi-poco-x5.webp",
    "title": "Smartphone",
    "wn": "5G",
    "isNew":true,
  }, {
    "id": 11,
    "product_name": "Samsung Galaxy A52",
    "make": "Samsung",
    "memory": "128GB",
    "os": "Android",
    "ram": "8GB",
    "price": 275,
    "image": "/Images/smartphones/samsung-galaxy-a52-8-128.jpg",
    "title": "Smartphone",
    "wn": "5G",
  }, {
    "id": 12,
    "product_name": "Samsung Galaxy A52",
    "make": "Samsung",
    "memory": "128GB",
    "os": "Android",
    "ram": "6GB",
    "price": 264,
    "image": "/Images/smartphones/samsung-galaxy-a52-6-128.png",
    "title": "Smartphone",
    "wn": "5G",
  }, {
    "id": 13,
    "product_name": "Samsung Galaxy A51",
    "make": "Samsung",
    "memory": "128GB",
    "os": "Android",
    "ram": "6GB",
    "price": 210,
    "image": "/Images/smartphones/samsung-galaxy-a51-6-128.jpg",
    "title": "Smartphone",
    "wn": "5G",
  }, {
    "id": 14,
    "product_name": "Samsung Galaxy A34",
    "make": "Samsung",
    "memory": "128GB",
    "os": "Android",
    "ram": "6GB",
    "price": 270,
    "image": "/Images/smartphones/samsung-galaxy-a34-5g.jpg",
    "title": "Smartphone",
    "wn": "5G",
  }, {
    "id": 15,
    "product_name": "Samsung Galaxy A13",
    "make": "Samsung",
    "memory": "64GB",
    "os": "Android",
    "ram": "4GB",
    "price": 130,
    "image": "/Images/smartphones/samsung-galaxy-a13.jpg",
    "title": "Smartphone",
    "wn": "5G",
  }, {
    "id": 16,
    "product_name": "Samsung Galaxy S8",
    "make": "Samsung",
    "memory": "64GB",
    "os": "Android",
    "ram": "4GB",
    "price": 295,
    "image": "/Images/smartphones/samsung-galaxy-s8.jpg",
    "title": "Smartphone",
    "wn": "4G",
  }, {
    "id": 17,
    "product_name": "Samsung Galaxy S23 Ultra",
    "make": "Samsung",
    "memory": "256GB",
    "os": "Android",
    "ram": "12GB",
    "price": 1000,
    "image": "/Images/smartphones/samsung-galaxy-s23-ultra.webp",
    "title": "Smartphone",
    "wn": "5G",
    "isNew":true,
  }, {
    "id": 18,
    "product_name": "Samsung Galaxy S23",
    "make": "Samsung",
    "memory": "128GB",
    "os": "Android",
    "ram": "8GB",
    "price": 600,
    "image": "/Images/smartphones/samsung-galaxy-s23.jpg",
    "title": "Smartphone",
    "wn": "5G",
  }, {
    "id": 19,
    "product_name": "Samsung Galaxy S22 Ultra",
    "make": "Samsung",
    "memory": "128GB",
    "os": "Android",
    "ram": "8GB",
    "price": 800,
    "image": "/Images/smartphones/samsung-galaxy-s22-ultra.jpg",
    "title": "Smartphone",
    "wn": "5G",
  }, {
    "id": 20,
    "product_name": "Samsung Galaxy S22 Ultra",
    "make": "Samsung",
    "memory": "256GB",
    "os": "Android",
    "ram": "12GB",
    "price": 850,
    "image": "/Images/smartphones/samsung-galaxy-s22-ultra12ram.jpg",
    "title": "Smartphone",
    "wn": "5G",
  }, {
    "id": 21,
    "product_name": "iPhone 14Pro Max",
    "make": "Apple",
    "memory": "128GB",
    "os": "iOS",
    "ram": "6GB",
    "price": 1180,
    "image": "/Images/smartphones/iphone-14pro-max-128.jpg",
    "title": "Smartphone",
    "wn": "5G",
    "isNew":true,
  }, {
    "id": 22,
    "product_name": "iPhone 14Pro",
    "make": "Apple",
    "memory": "256",
    "os": "iOS",
    "ram": "6GB",
    "price": 1180,
    "image": "/Images/smartphones/iphone-14-pro-256.jpg",
    "title": "Smartphone",
    "wn": "5G",
    "isNew":true,
  }, {
    "id": 23,
    "product_name": "iPhone 14Pro",
    "make": "Apple",
    "memory": "128GB",
    "os": "iOS",
    "ram": "6GB",
    "price": 1080,
    "image": "/Images/smartphones/iphone-14-pro-128.jpg",
    "title": "Smartphone",
    "wn": "5G",
  }, {
    "id": 24,
    "product_name": "iPhone 13 Mini",
    "make": "Apple",
    "memory": "128GB",
    "os": "iOS",
    "ram": "6GB",
    "price": 620,
    "image": "/Images/smartphones/iphone-13-mini.jpg",
    "title": "Smartphone",
    "wn": "5G",
  }, {
    "id": 25,
    "product_name": "iPhone 6S",
    "make": "Apple",
    "memory": "64GB",
    "os": "iOS",
    "ram": "2GB",
    "price": 160,
    "image": "/Images/smartphones/iphone-6s-2ram.jpg",
    "title": "Smartphone",
    "wn": "4G",
  }, {
    "id": 26,
    "product_name": "HONOR X8",
    "make": "Honor",
    "memory": "128GB",
    "os": "Android",
    "ram": "6GB",
    "price": 175,
    "image": "/Images/smartphones/honor-x8.jpg",
    "title": "Smartphone",
    "wn": "5G",
  }, {
    "id": 27,
    "product_name": "HONOR X7",
    "make": "Honor",
    "memory": "128GB",
    "os": "Android",
    "ram": "4GB",
    "price": 160,
    "image": "/Images/smartphones/honor-x7.jpg",
    "title": "Smartphone",
    "wn": "4G",
  }, {
    "id": 28,
    "product_name": "HONOR X6",
    "make": "Honor",
    "memory": "64GB",
    "os": "Android",
    "ram": "4GB",
    "price": 155,
    "image": "/Images/smartphones/honor-x6.jpg",
    "title": "Smartphone",
    "wn": "4G",
  }, {
    "id": 29,
    "product_name": "HONOR 70",
    "make": "Honor",
    "memory": "256GB",
    "os": "Android",
    "ram": "8GB",
    "price": 410,
    "image": "/Images/smartphones/honor-70.jpg",
    "title": "Smartphone",
    "wn": "5G",
    "isNew":true,
  }, {
    "id": 30,
    "product_name": "HONOR 50 Lite",
    "make": "Honor",
    "memory": "128GB",
    "os": "Android",
    "ram": "6GB",
    "price": 165,
    "image": "/Images/smartphones/honor-50-lite.png",
    "title": "Smartphone",
    "wn": "4G",
    "isNew":true,
  }]


export const smartphones = data